### ISSUE TITLE
Please add demos to docs

### ISSUE THREAD

**Issue by ghost** [ThrivingKings/animo#15]
Pretty please? I'm avoiding Yarn like the plague.

**Comment by ThrivingKings** [comment]
I went back and forth on this but I can see the value they'd add. Thanks

**Comment by ghost** [comment]
You'd save a lot of people, a lot of time. I ask because I was landed here from a Speckyboy article but had to pass on by because I'm trying to GSD done. FWIW I'm also [compiling a list](https://habd.as/jamstack-css-framework-tool-library/), and for the sake of the readers, I question the value of sending them to an animation library which didn't show them how it mades animation.

**Comment by ThrivingKings** [comment]
Oh, I see. That's probably where the confusion lies. I think that article is referencing the old library (https://github.com/ThrivingKings/animo.js) which was a jQuery plugin that _could_ be considered an animation library. Nowadays, animo is more of a developer tool, allowing you to use transitions to chain together complex animations. The packages that are included are more along the lines of examples of what it's capable of. I still do plan on bringing the demos back, when I've got some free-time.

**Comment by ghost** [comment]
That sounds awesome. Both what it does and just seeing a stress test demo. Thank you kindly.

**Comment by ghost** [comment]
@ThrivingKings I took another look at the docs and realize the first time through I didn't see the arrows on the side due to the similarity in contrast with the page background. And now I see this library supports promises which is exactly what I needed. \o/

**Comment by ThrivingKings** [comment]
Oh, cool, glad to hear! I hope it helps and don't hesitate to reach out with any questions. I can't promise I'll be able to respond immediately, but I'll definitely try! :)

**Comment by jhabdas** [comment]
You betcha. Just added you to a new list (don't we all love them?) I'm putting together for the JAMstack save that's about to hit us: https://habd.as/jamstack-css-framework-tool-library/. I'll try and get you an example of the work when I'm wrapping up the title sequence.

**Comment by ThrivingKings** [comment]
Very cool and very much appreciated!

**Comment by ghost** [comment]
Promises worked beautifully. Animations were a cinch. Now I'm just regretting the hours I dumped making spaghetti with animateplus: https://security7.net/
