### ISSUE TITLE
[animo/animate] A little on the Hefty Side

### ISSUE THREAD

**Issue by ghost** [ThrivingKings/animo#17]
I love it. But it's a little chunky weighing in at 116KB minified ([example](https://security7.net)). Thoughts on repackaging with a different bundler to see if we can slim this puppy down a little? (Please disregard [how I'm loading it](https://www.npmjs.com/package/fetch-inject) right now.)

![security7.net](https://cloud.githubusercontent.com/assets/440298/25044861/aa97bd7c-215b-11e7-9885-eea39c79c5a5.png "Loading jQuery, Transit, Hover Intent, Superfish, Animo and main JS asynchronously in parallel")

**Comment by ThrivingKings** [comment]
Yes, good call. I've been considering switching to rollup so let me give it a shot and see what I can come up with. Thanks!

**Comment by jhabdas** [comment]
Solid.

**Comment by ThrivingKings** [comment]
Just wanted to give you a quick update. I've been experimenting and it looks like I might be able to shave at least 30kb off of the build. I have some more ideas and want to work on it a bit more but I'm hoping to publish something within the next couple of days

**Comment by ThrivingKings** [comment]
You can follow along here: https://github.com/ThrivingKings/animo/pull/18

Thanks for calling me out on this— the bundles were unnecessarily large. I still have some tinkering to do before I call it good, but right now I'm seeing bundles around 18kb total :)

**Comment by ghost** [comment]
Much appreciate the quick action. You need a PR reviewer feel free to ping.

**Comment by ThrivingKings** [comment]
sorry, this took longer than I thought it would, but all bundles are checking in around 18kb, so way better than before. it all checked out on my end but let me know if you have any issues with https://github.com/ThrivingKings/animo/releases/tag/v1.0.8

**Comment by jhabdas** [comment]
![img_4689](https://cloud.githubusercontent.com/assets/440298/25305052/00fa8090-27a7-11e7-9aea-d5e3bde8c88a.JPG) thanks hoss
