### ISSUE TITLE
Requiring from Node returns `{}`

### ISSUE THREAD

**Issue by agj** [ThrivingKings/animo#20]
Animo seems to be just what I was looking for. However, it doesn't seem to be working for me. I guess it works when used with Webpack and ES6 imports? It doesn't for me with Node v9.11.1, bundling with Browserify. The `require()` just returns an empty object...

**Comment by ThrivingKings** [comment]
Hi, sorry, I've been traveling. Are you using babel to transpile? Maybe try sourcing the `lib/index.js` from the package?

**Comment by agj** [comment]
I'm not transpiling. Are you making it a requirement? And I can't see the file you mention in your repo...?

I solved the problem for me by just manually modifying the code and turning it into a CommonJS module.

**Comment by ThrivingKings** [comment]
The `lib` directory is in the built version, in the npm package. Yeah, ES6 `import` kind of handcuffs us to transpiling

Glad to hear you found a workaround. I'm going to close this out. Thanks!
