### ISSUE TITLE
sequencing animation

### ISSUE THREAD

**Issue by agmuntean** [ThrivingKings/animo#7]
Hi,

Sorry to bother but I'd really like to use animo to sequence my css animation. The usage explanation on animojs.com is pretty vague and I couldn't figure out how to use it. It would be great if you could provide some demos.

Thanks a lot,
Adrian

**Comment by ThrivingKings** [comment]
Hi, truly sorry for the delayed response! Can you explain your situation a little more? What are you trying to accomplish?

**Comment by agmuntean** [comment]
Hi thanks for the reply. Basically this is what my problem was: 
- I created the CSS animations for different elements based on some classes that will trigger the animation
- I just needed a JS script to add/remove/toggle these classes in a specific order and at a specific timing. I could accomplished this with a very ugly and less automated combination of jquerry and css animation-delay. 

I thought I could use anime to do just that, but I could'n figure out?  

This is my code: 
`$(document).ready(function () {
  function loadingAnimation() {
    $('.ext-wrap').removeClass('loading').addClass('loaded');
  }
  setTimeout(loadingAnimation, 5500);

  function cssDefault() {
    $('body').removeClass('animate');
    $('.ext-wrap').removeClass('loaded');
  }
  setTimeout(cssDefault, 9500);

  $('.menu-icon__wrap').click(function () {
    $('.nav__wrap').addClass('nav__wrap--open');
  });

  $('.btn__close').click(function () {
    $('.nav__wrap').removeClass('nav__wrap--open');
  });

  $('.nav__page .menu__item').click(function () {
    $('.nav__wrap').removeClass('nav__wrap--open');
  });

  $('.menu__item--active > a').click(function () {
    $('.nav__wrap').toggleClass('nav__wrap--open');
  });
});`

Thanks,
Adrian

**Comment by ThrivingKings** [comment]
The old animo library (https://github.com/ThrivingKings/animo.js) could do this. You'll probably be interested in `animationEnd` listeners (https://developer.mozilla.org/en-US/docs/Web/Events/animationend)
